// Generated by CoffeeScript 1.6.3
(function() {
  var Client, Http, Mpeg, Source,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Mpeg = require("../formats/mpeg").Mpeg;

  Http = require("../http").Http;

  Client = Mpeg.Client, Source = Mpeg.Source;

  Http.Handler.Mpeg = (function(_super) {
    __extends(Mpeg, _super);

    function Mpeg() {
      Mpeg.__super__.constructor.apply(this, arguments);
      this.on("metadata", function(metadata) {
        var _ref;
        return (_ref = this.source) != null ? _ref.onMetadata(metadata) : void 0;
      });
    }

    Mpeg.prototype.createClient = function(req, res, done) {
      var client, icyMetadata, _ref;
      if (req.get("Icy-MetaData") === "1") {
        icyMetadata = true;
      } else {
        icyMetadata = false;
      }
      client = new Client({
        icyMetadata: icyMetadata,
        metadata: (_ref = this.source) != null ? _ref.metadata : void 0,
        destination: res
      });
      if (icyMetadata) {
        res.set("icy-metaint", client.icyMetadataInterval);
      }
      res.set("Content-Type", "audio/mpeg");
      return done(client);
    };

    Mpeg.prototype.createSource = function() {
      return this.source = new Source;
    };

    return Mpeg;

  })(Http.Handler);

}).call(this);
