// Generated by CoffeeScript 1.6.3
(function() {
  var HttpHandler, Ogg, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Ogg = require("../formats/ogg").Ogg;

  HttpHandler = require("../http").HttpHandler;

  module.exports.Ogg = Ogg;

  Ogg.HttpHandler = (function(_super) {
    __extends(HttpHandler, _super);

    function HttpHandler() {
      _ref = HttpHandler.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HttpHandler.prototype.createClient = function(req, res, done) {
      var client;
      client = new Ogg.Client({
        source: this.source,
        destination: res
      });
      return client.headerOut(function() {
        return done(client);
      });
    };

    HttpHandler.prototype.createSource = function() {
      return this.source = new Ogg.Source;
    };

    return HttpHandler;

  })(HttpHandler);

}).call(this);
