// Generated by CoffeeScript 1.6.3
(function() {
  var Client, Http, Ogg, Source, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Ogg = require("../formats/ogg").Ogg;

  Http = require("../http").Http;

  Client = Ogg.Client, Source = Ogg.Source;

  Http.Handler.Ogg = (function(_super) {
    __extends(Ogg, _super);

    function Ogg() {
      _ref = Ogg.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Ogg.prototype.createClient = function(req, res, done) {
      var client;
      client = new Client({
        source: this.source,
        destination: res
      });
      return client.headerOut(function() {
        return done(client);
      });
    };

    Ogg.prototype.createSource = function() {
      return this.source = new Source;
    };

    return Ogg;

  })(Http.Handler);

}).call(this);
