// Generated by CoffeeScript 1.6.3
(function() {
  var PassThrough,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PassThrough = require("stream").PassThrough;

  module.exports.Client = (function(_super) {
    __extends(Client, _super);

    function Client(opts) {
      if (opts == null) {
        opts = {};
      }
      Client.__super__.constructor.call(this, {
        highWaterMark: opts.queueSize || 524288
      });
      if (opts.destination != null) {
        this.pipe(opts.destination);
      }
      this.on("metadata", function(metadata) {
        return this.metadata = metadata;
      });
      this.on("data", function() {});
    }

    return Client;

  })(PassThrough);

  require("./formats/mpeg");

  require("./formats/ogg");

}).call(this);
