// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require("events").EventEmitter;

  module.exports.HttpHandler = (function(_super) {
    __extends(HttpHandler, _super);

    function HttpHandler(app, mount) {
      this.app = app;
      this.mount = mount;
      this.source = this.createSource();
    }

    HttpHandler.prototype.serveClient = function(req, res) {
      var _this = this;
      return this.createClient(req, res, function(client) {
        _this.source.addClient(client);
        return res.on("end", function() {
          return _this.source.removeClient(client);
        });
      });
    };

    return HttpHandler;

  })(EventEmitter);

}).call(this);
