// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmitter, Http,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require("events").EventEmitter;

  module.exports.Http = Http = {};

  Http.Handler = (function(_super) {
    __extends(Handler, _super);

    function Handler(app, mount) {
      this.app = app;
      this.mount = mount;
      this.source = this.createSource();
    }

    Handler.prototype.serveClient = function(req, res) {
      var _this = this;
      return this.createClient(req, res, function(client) {
        _this.source.pipe(client);
        return res.on("close", function() {
          return _this.source.unpipe(client);
        });
      });
    };

    return Handler;

  })(EventEmitter);

  require("./http/mpeg");

  require("./http/ogg");

}).call(this);
