// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, serveSource;

  serveSource = require("./connect");

  express = require("express");

  app = express();

  app.post("/:mount", serveSource(app));

  app.listen(8000);

}).call(this);
