// Generated by CoffeeScript 1.6.3
(function() {
  var MpegClient, Source, app, express, source;

  MpegClient = require("./clients/mpeg").MpegClient;

  Source = require("./source").Source;

  express = require("express");

  source = null;

  app = express();

  app.get("/source", function(req, res) {
    var client, icyMetadata;
    if (source == null) {
      return res.status(404).end("no source!");
    }
    if (req.get("Icy-MetaData") === "1") {
      icyMetadata = true;
    } else {
      icyMetadata = false;
    }
    client = new MpegClient({
      icyMetadata: icyMetadata,
      destination: res
    });
    if (icyMetadata) {
      res.set("icy-metaint", client.icyMetadataInterval);
    }
    res.set("Content-Type", "audio/mpeg");
    source.addClient(client);
    return res.on("end", function() {
      return source.removeClient(client);
    });
  });

  app.post("/source", function(req, res) {
    if (source != null) {
      return res.status(503).end("mount point taken!");
    }
    source = new Source;
    req.on("end", function() {
      return source = null;
    });
    req.pipe(source);
    return res.send("Thanks, brah!");
  });

  app.get("/admin/metadata", function(req, res) {
    source.emit("metadata", {
      title: req.query.title,
      artist: req.query.artist
    });
    return res.send("Thanks, brah!");
  });

  app.listen(8000);

}).call(this);
