// Generated by CoffeeScript 1.6.3
(function() {
  var Client, Express, Http, Source;

  Client = require("./client").Client;

  Express = require("./express").Express;

  Http = require("./http").Http;

  Source = require("./source").Source;

  module.exports.Nodecaster = {
    Client: Client,
    Express: Express,
    Http: Http,
    Source: Source
  };

}).call(this);
