// Generated by CoffeeScript 1.6.3
(function() {
  var PassThrough, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require("underscore");

  PassThrough = require("stream").PassThrough;

  module.exports.Source = (function(_super) {
    __extends(Source, _super);

    function Source(opts) {
      if (opts == null) {
        opts = {};
      }
      Source.__super__.constructor.apply(this, arguments);
      this.on("data", function() {});
      this.clients = [];
      this.setMaxListeners(0);
    }

    Source.prototype.addClient = function(client) {
      this.clients.push(client);
      return this.pipe(client);
    };

    Source.prototype.removeClient = function(client) {
      this.clients = _.without(this.clients, client);
      return this.unpipe(client);
    };

    return Source;

  })(PassThrough);

}).call(this);
